name: Custom lint
description: Activates and runs custom lints

inputs:
  working-directory:
    description: The working-directory to run custom lints on.
    default: "."
    required: false

runs:
  using: composite
  steps:
    - name: Activate custom_lint cli
      shell: bash
      run: dart pub global activate custom_lint
    - name: Run custom_lint cli
      shell: bash
      run: cd ${{ inputs.working-directory }} && custom_lint
