name: alf_lints
description: Opinionated Dart lints to maintain a clean application structure.
version: 1.0.0
homepage: https://github.com/saibot-l/alf-lints
repository: https://github.com/saibot-l/alf-lints
issue_tracker: https://github.com/saibot-l/alf-lints/issues
topics:
  - app-architecture
  - folder-structure
  - lints

environment:
  sdk: ^3.4.0

dependencies:
  analyzer: ^6.5.0
  analyzer_plugin: ^0.11.3
  custom_lint_builder: ^0.6.4

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.2
