name: alf_lints
description: Opinionated Dart lints to maintain a clean application structure.
version: 1.0.0
homepage: https://github.com/saibot-l/alf-lints
repository: https://github.com/saibot-l/alf-lints
issue_tracker: https://github.com/saibot-l/alf-lints/issues

environment:
  sdk: ^3.3.1

dependencies:
  analyzer: ^6.4.1
  analyzer_plugin: ^0.11.3
  custom_lint_builder: ^0.6.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
