name: alf_lints
description: Opinionated Dart lints to maintain a clean application structure.
version: 1.0.0
repository: https://github.com/saibot-l/alf-lints

environment:
  sdk: ^3.3.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
