name: example_app
description: Examples of the alf-lints.
publish_to: 'none'

environment:
  sdk: ^3.3.1

dependencies:
  example_package_feature:
    path: ../../packages/features/example_package_feature
  example_package_library:
    path: ../../packages/libraries/example_package_library

dev_dependencies:
  alf_lints:
    path: ../../..
  custom_lint: ^0.6.2
  lints: ^3.0.0
